language: node_js
node_js: stable

sudo: false

os:
  - linux

before_script:
  - npm install

notifications:
  email: false

cache:
  directories:
    - node_modules

script:
  -  ng test --karma-config src/karma.conf.ci.js
