language: node_js
node_js: stable

sudo: false

os:
  - linux

before_script:
  - npm install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5

notifications:
  email: false

cache:
  directories:
    - node_modules

script:
  -  npm run test
